package plf.s02_oop_class_design.s02_06_method_design;

// EXERCISE: this test starts red — fix Schedule.java, do NOT edit this file.

import static org.junit.jupiter.api.Assertions.assertEquals;
import static org.junit.jupiter.api.Assertions.assertThrows;

import java.time.LocalDate;
import java.time.LocalTime;
import java.util.ArrayList;
import java.util.List;
import org.junit.jupiter.api.Test;

class ScheduleTest {

    private static final LocalTime NINE = LocalTime.of(9, 0);
    private static final LocalTime MIDNIGHT = LocalTime.MIDNIGHT;

    @Test
    void q1_immutableArm_callerMutatingItsListDoesNotLeak() {
        List<LocalDate> caller = new ArrayList<>();
        caller.add(LocalDate.of(2026, 1, 1));
        Schedule schedule = new Schedule(caller, List.of());

        caller.add(LocalDate.of(2026, 2, 2));

        assertEquals(1, schedule.days().size());
    }

    @Test
    void q2_mutableArm_callerMutatingAnAppointmentMustNotLeakIn() {
        Appointment appt = new Appointment(NINE);
        List<Appointment> caller = new ArrayList<>();
        caller.add(appt);
        Schedule schedule = new Schedule(List.of(), caller);

        appt.setTime(LocalTime.of(23, 59));

        assertEquals(NINE, schedule.appointments().get(0).getTime());
    }

    @Test
    void q3_mutableArm_mutatingViaReturnedListMustNotLeakOut() {
        Schedule schedule = new Schedule(List.of(), List.of(new Appointment(NINE)));

        schedule.appointments().get(0).setTime(MIDNIGHT);

        assertEquals(NINE, schedule.appointments().get(0).getTime());
    }

    @Test
    void returnedCollectionsAreUnmodifiable() {
        Schedule schedule = new Schedule(List.of(), List.of(new Appointment(NINE)));

        assertThrows(UnsupportedOperationException.class,
                () -> schedule.appointments().add(new Appointment(MIDNIGHT)));
    }
}
