package plf.s01_core_language.s01_08_numbers_and_math;

import org.junit.jupiter.api.DisplayName;
import org.junit.jupiter.api.Test;

import java.math.BigDecimal;

import static org.junit.jupiter.api.Assertions.assertEquals;
import static org.junit.jupiter.api.Assertions.assertTrue;

// Do NOT edit this file. Fix the production code in PriceBook.java until green.
@DisplayName("The Rounding Heist")
class PriceBookTest {

    @Test
    @DisplayName("R1: 1.005 rounds HALF_UP to 1.01, not 1.00")
    void singlePriceRoundsHalfUp() {
        BigDecimal total = PriceBook.roundedTotal(java.util.List.of(1.005));
        assertEquals(new BigDecimal("1.01"), total,
                "1.005 must round HALF_UP to 1.01; if you see 1.00 the value was poisoned by new BigDecimal(double)");
    }

    @Test
    @DisplayName("R1b: a basket of .005 prices rounds correctly")
    void basketRoundsHalfUp() {
        BigDecimal total = PriceBook.roundedTotal(java.util.List.of(1.005, 2.005, 3.005));
        assertEquals(new BigDecimal("6.02"), total);
    }

    @Test
    @DisplayName("R2: 1.0 and 1.00 are the same amount")
    void sameValueDifferentScale() {
        assertTrue(PriceBook.sameAmount(new BigDecimal("1.0"), new BigDecimal("1.00")),
                "same value, different scale must be equal by amount (compareTo == 0, not equals)");
    }

    @Test
    @DisplayName("R2b: different amounts are not equal")
    void differentValuesAreNotSame() {
        org.junit.jupiter.api.Assertions.assertFalse(
                PriceBook.sameAmount(new BigDecimal("1.00"), new BigDecimal("1.01")));
    }

    @Test
    @DisplayName("R3: splitting 1.00 across 3 people does not throw and rounds to 0.33")
    void perPersonShareDoesNotThrow() {
        BigDecimal share = PriceBook.perPersonShare(new BigDecimal("1.00"), 3);
        assertEquals(new BigDecimal("0.33"), share,
                "divide() needs a scale + RoundingMode or it throws ArithmeticException on 1/3");
    }
}
